/// <reference types="nativewind/types" />

declare module '@env' {
  export const GOOGLE_MAPS_API_KEY: string;
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.